# Dockerfile for guacamole, forked from oznu/docker-guacamole
#
# Maintained by Antoine Besnier <nouanda@laposte.net>
#

FROM library/tomcat:10.1.0-jre11

ENV GUACAMOLE_HOME=/app/guacamole \
  PGDATA=/config/postgres \
  POSTGRES_USER=guacamole \
  POSTGRES_DB=guacamole_db \
  S6OVERLAY_VER=3.1.2.1 \
  POSTGREJDBC_VER=42.5.0 \
  GUAC_VER=1.4.0 \
  PG_MAJOR=14

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends\
      curl \
      git \
      xz-utils

# Apply the s6-overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6OVERLAY_VER}/s6-overlay-noarch.tar.xz /tmp/
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6OVERLAY_VER}/s6-overlay-x86_64.tar.xz /tmp/
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6OVERLAY_VER}/s6-overlay-aarch64.tar.xz /tmp/
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6OVERLAY_VER}/s6-overlay-symlinks-noarch.tar.xz /tmp/
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6OVERLAY_VER}/syslogd-overlay-noarch.tar.xz /tmp/
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz \
    && if [ "$(arch)" = "x86_64" ] ; then tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz; else tar -C / -Jxpf /tmp/s6-overlay-aarch64.tar.xz; fi  \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/syslogd-overlay-noarch.tar.xz \
    && rm /tmp/*.tar.xz

# Create guacamole directories
RUN mkdir -p ${GUACAMOLE_HOME} \ 
              ${GUACAMOLE_HOME}/lib \
              ${GUACAMOLE_HOME}/extensions \
              ${GUACAMOLE_HOME}/extensions-available

WORKDIR ${GUACAMOLE_HOME}

# Add PostGresql repository & Install dependencies
RUN apt-get update && apt-get upgrade -y -t jammy-backports && \
      apt-get install -y \
      freerdp2-dev \
      ghostscript \
      libavcodec-dev \
      libavformat-dev \
      libavutil-dev \
      libcairo2-dev \
      libfreerdp-client2-2 \
      libjpeg-dev \
      libjpeg-turbo8-dev \
      libossp-uuid-dev \
      libpango1.0-dev \
      libpng-dev \
      libpulse-dev \
      libssh2-1-dev \
      libssl-dev \
      libswscale-dev \
      libtelnet-dev \
      libtool-bin \
      libvncserver-dev \
      libvorbis-dev \
      libwebp-dev \
      libwebsockets-dev \
      make \
      postgresql-${PG_MAJOR}

# Link FreeRDP to where guac expects it to be
RUN ln -s /usr/local/lib/freerdp /usr/lib/arm-linux-gnueabihf/freerdp || exit 0 \
    && ln -s /usr/local/lib/freerdp /usr/lib/x86_64-linux-gnu/freerdp || exit 0 \
    && ln -s /usr/local/lib/freerdp /usr/lib/aarch64-linux-gnu/freerdp || exit 0

# Install guacamole-server
RUN mkdir /git \
  && cd /git && git clone https://github.com/apache/guacamole-server.git --depth=1 -b master \
  && cd guacamole-server \
  && autoreconf -fi \
  && ./configure --enable-allow-freerdp-snapshots \
  && make -j$(getconf _NPROCESSORS_ONLN) \
  && make install \
  && cd .. \
  && rm -rf guacamole-server-${GUAC_VER}.tar.gz guacamole-server-${GUAC_VER} \
  && ldconfig \
# Install guacamole-client and postgres auth adapter
  && set -xe \
  && rm -rf ${CATALINA_HOME}/webapps/ROOT \
  && curl -SLo ${CATALINA_HOME}/webapps/ROOT_tomcat9.war "https://dlcdn.apache.org/guacamole/${GUAC_VER}/binary/guacamole-${GUAC_VER}.war" \
  && curl -SLo /tmp/jakartaee-migration-shaded.jar "https://dlcdn.apache.org/tomcat/jakartaee-migration/v1.0.4/binaries/jakartaee-migration-1.0.4-shaded.jar" \
  && java -jar /tmp/jakartaee-migration-shaded.jar ${CATALINA_HOME}/webapps/ROOT_tomcat9.war ${CATALINA_HOME}/webapps/ROOT.war \
  && rm ${CATALINA_HOME}/webapps/ROOT_tomcat9.war \
  && curl -SLo ${GUACAMOLE_HOME}/lib/postgresql-${POSTGREJDBC_VER}.jar "https://jdbc.postgresql.org/download/postgresql-${POSTGREJDBC_VER}.jar" \                
  && curl -SLO "https://dlcdn.apache.org/guacamole/${GUAC_VER}/binary/guacamole-auth-jdbc-${GUAC_VER}.tar.gz" \
  && tar -xzf guacamole-auth-jdbc-${GUAC_VER}.tar.gz \
  && java -jar /tmp/jakartaee-migration-shaded.jar guacamole-auth-jdbc-${GUAC_VER}/postgresql/guacamole-auth-jdbc-postgresql-${GUAC_VER}.jar guacamole-auth-jdbc-${GUAC_VER}/postgresql/guacamole-auth-jdbc-postgresql-${GUAC_VER}-tomcat10.jar \
  && cp -R guacamole-auth-jdbc-${GUAC_VER}/postgresql/guacamole-auth-jdbc-postgresql-${GUAC_VER}.jar ${GUACAMOLE_HOME}/extensions/guacamole-auth-jdbc-postgresql-${GUAC_VER}.jar  \
  && cp -R guacamole-auth-jdbc-${GUAC_VER}/postgresql/schema ${GUACAMOLE_HOME}/ \
  && rm -rf guacamole-auth-jdbc-${GUAC_VER} guacamole-auth-jdbc-${GUAC_VER}.tar.gz \
# Add optional extensions
  && for i in auth-duo auth-quickconnect auth-header auth-ldap auth-json auth-totp; do \         
    echo "https://dlcdn.apache.org/guacamole/${GUAC_VER}/binary/guacamole-${i}-${GUAC_VER}.tar.gz" \
    && curl -SLO "https://dlcdn.apache.org/guacamole/${GUAC_VER}/binary/guacamole-${i}-${GUAC_VER}.tar.gz" \
    && tar -xzf guacamole-${i}-${GUAC_VER}.tar.gz \
    && cp guacamole-${i}-${GUAC_VER}/guacamole-${i}-${GUAC_VER}.jar ${GUACAMOLE_HOME}/extensions-available/ \
    && java -jar /tmp/jakartaee-migration-shaded.jar ${GUACAMOLE_HOME}/extensions-available/guacamole-${i}-${GUAC_VER}.jar ${GUACAMOLE_HOME}/extensions-available/guacamole-${i}-${GUAC_VER}-tomcat10.jar  \
    && rm ${GUACAMOLE_HOME}/extensions-available/guacamole-${i}-${GUAC_VER}.jar \
    && mv ${GUACAMOLE_HOME}/extensions-available/guacamole-${i}-${GUAC_VER}-tomcat10.jar  ${GUACAMOLE_HOME}/extensions-available/guacamole-${i}-${GUAC_VER}.jar \
    && rm -rf guacamole-${i}-${GUAC_VER} guacamole-${i}-${GUAC_VER}.tar.gz \
  ;done \
# Special case for SSO extension as it bundles CAS, SAML and OpenID in subfolders
# I keep the for loop, just in case future releases of guacamole bundles other extensions...
  && curl -SLO "https://dlcdn.apache.org/guacamole/${GUAC_VER}/binary/guacamole-auth-sso-${GUAC_VER}.tar.gz" \
  && tar -xzf guacamole-auth-sso-${GUAC_VER}.tar.gz \
  && for i in cas openid saml; do \
    cp guacamole-auth-sso-${GUAC_VER}/${i}/guacamole-auth-sso-${i}-${GUAC_VER}.jar ${GUACAMOLE_HOME}/extensions-available/ \
  ;done \
  && rm -rf guacamole-auth-sso-${GUAC_VER} guacamole-auth-sso-${GUAC_VER}.tar.gz \
# Clean-up
    && apt-get purge -y binutils curl git make \
    && apt-get autoremove --purge -y \
    && apt-get autoclean -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* /var/tmp/* ~/.m2 /git

ENV PATH=/usr/lib/postgresql/${PG_MAJOR}/bin:$PATH
ENV GUACAMOLE_HOME=/config/guacamole

COPY root_pg14 /

WORKDIR /config

EXPOSE 8080

ENTRYPOINT [ "/init" ]
